---

# TODO: Choose a disklabel type based on platform and disk size.
#
- name: Install parted command as needed
  package:
    name: parted
    state: present
  register: parted_pkg
  when: "'parted' not in installed_packages and use_partitions and volume.type != 'disk'"

- set_fact:
    installed_packages: "{{ installed_packages + ['parted'] }}"
  when: parted_pkg is defined

- name: Create disklabels as needed
  parted:
    device: "{{ item }}"
    label: "gpt"
    state: "{{ state }}"
  when: use_partitions and volume.type != 'disk'
  loop: "{{ disks }}"
