---
- name: Install LVM2 commands as needed
  package:
    name: lvm2
    state: present
  when: "'lvm2' not in installed_packages and device_type == 'lvm'"

- set_fact:
    installed_packages: "{{ installed_packages + ['lvm2'] }}"
  when: 'lvm2' not in installed_packages

- name: Make sure LV exists
  lvol:
    lv: "{{ device_name }}"
    vg: "{{ lvm_vg }}"
    size: "{{ parsed_size.lvm }}"
    state: "{{ state }}"
    force: yes
    shrink: no
  when: device_type == "lvm" and lvm_vg
